name: Publish Site
on:
  push:
    branches:
      - master
  schedule:
   - cron: 0 20 * * *
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install deps
        run: |
              npm install postcss-cli
              npm install autoprefixer
              curl https://raw.githubusercontent.com/rancher-sandbox/cOS-toolkit/master/scripts/get_luet.sh | sudo bash -
              sudo luet install -y toolchain/yq
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          hugoVersion: extended_0.82.0
